services:
  guitars-database:
    image: postgres:alpine
    container_name: guitars-database
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guitars